---
ami: "{{ redhat_ami }}"
instance_type: "t2.micro"
tag_expireon: "2017-09-30"
data_vol_size: 30
group_name: "group_name"
app_name: "app_name"
replset_prefix: "rs"
server_number: "01"
ssh_user: "ec2-user"
tag_owner: "your_name"
fqdn_domain: "your_domain"

instance_name: "{{ group_name }}_{{ app_name }}_{{replset_prefix}}{{ server_number }}"
server_group_name: "{{ group_name}}_{{ app_name }}_{{replset_prefix}}"
fqdn: "{{instance_name}}.{{ fqdn_domain }}"

region: "us-west-2"
security_key: "your_key"
security_group: "your_security_group"

vpc_subnet_id: ""
assign_public_ip: "yes"

redhat_ami: "ami-9fa343e7"


availability_zone: "{{ region }}c"
create_data_folder: True
data_folder: "/app/mongodb"
swap_location: /etc/xvdf
