---

- name: collecting the instance facts
  hosts: local
  tasks:
    - ec2_facts:
      register: current_instance

- name: perform checks to ensure all devices are mounted
  hosts: local
  vars:
    - instance_id: "{{current_instance.ansible_facts.ansible_ec2_instance_id}}"
  roles:
    - role: instance_checker
